# A volume claim is not a real volume but just an ADVERTISMENT which goes with the pods inside the same cluster. Each pod can choose a statically provisioned volume or a dynamic one
# a volume clain is an advertisement attached to a pod
# so for a pod config, it will say: " this pods needs a xGb storage" and we can imagin our pod config will be handed over to kubernetes and kubernetes will need to find an instance of storage inside the cluster that match with the volume requirement. if kubernetes does not have such an instance of storage (a slice of our hard drive) volume ready to go then it will try to create one on the fly and attach it to the pod that will be created.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database-persistent-volume-claim
spec:
    accessModes:
        - ReadWriteOnce
        # means that we want an instance of storage that can be used by a SINGLE node at a time
        # ReadOnlyMany -> multiple nodes can read from this persistent volume at the same time
        # ReadWriteMany -> can be read and written to by many nodes at the same time
    resources:
        requests:
            storage: 2Gi #kubernetes must find a storage of 2Gb of space

# below are other additional options we can use, however for our use case, we will rely on the default one -> see lesson 203
